Repository DeveloperAcademy-POSTECH/MacC-Team-Sandals, pull requests merged in 2022-12, with the labels that each got.

#79 큐레이션 커뮤니티 탭에 기존 작업(큐레이션 작성, 큐레이션 상세 페이지)를 합치고, 그 과정에서 발생하는 에러를 수정했습니다.
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/View Controllers/FeaturedCurationListViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
  Kindy/Kindy/View Controllers/SearchViewController.swift
  Kindy/Kindy/Views/CurationList/CurationListCell.swift
  Kindy/Kindy/Views/Nearby/NearbyCell.swift
Labels: bug, feature

#80 큐레이션 내부에서 댓글 로직 개선과, 큐레이션 작성 삭제 뷰컨트롤러와 연결을 하였습니다.
  Kindy/Kindy.xcodeproj/xcshareddata/xcschemes/Kindy.xcscheme
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Network Controllers/CommentRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/View Controllers/Curation/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateTitleView.swift
  Kindy/Kindy/Views/Curation/CurationButtonItem.swift
  Kindy/Kindy/Views/Curation/CurationButtonStackView.swift
  Kindy/Kindy/Views/Curation/CurationCommentCell.swift
  Kindy/Kindy/Views/Curation/CurationCommentTextFieldCell.swift
  Kindy/Kindy/Views/Curation/CurationHeaderView.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
Labels: feature

#81 디자인적인 디테일 수정 및 FirestoreRequest에 add, delete를 추가했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Assets.xcassets/KindyLogo.imageset/Contents.json
  Kindy/Kindy/Assets.xcassets/KindyLogo.imageset/KindyLogo.pdf
  Kindy/Kindy/Assets.xcassets/KindyLogo.imageset/KindyLogo.svg
  Kindy/Kindy/Base.lproj/LaunchScreen.storyboard
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Models/Bookstore/Bookstore.swift
  Kindy/Kindy/Models/Curation/Comment.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Home/ViewModel.swift
  Kindy/Kindy/Models/User.swift
  Kindy/Kindy/Network Controllers/BookstoreRequest.swift
  Kindy/Kindy/Network Controllers/CommentRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/Protocols/FirestoreRequest.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/SearchViewController.swift
  Kindy/Kindy/Views/Home/EmptyNearbyCell.swift
Labels: refactor, design

#82 이미지 비율이 깨지는 문제를 해결했습니다. + 기타 리팩토링
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UIImage+.swift
  Kindy/Kindy/Extensions/Utility/Constants.swift
  Kindy/Kindy/Models/Bookstore/Bookstore.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/ImageCache.swift
  Kindy/Kindy/Network Controllers/CommentRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Protocols/BarAppearanceDelegate.swift
  Kindy/Kindy/Protocols/FirestoreRequest.swift
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/FeaturedCurationListViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/My Page/WritingListViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
  Kindy/Kindy/View Controllers/SearchViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
Labels: bug, refactor

#83 Request 구조체들, ImageCache, HomeViewController를 리팩토링했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Models/ImageCache.swift
  Kindy/Kindy/Network Controllers/CommentRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/Protocols/FirestoreRequest.swift
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Home/HomViewController+Delegates.swift
  Kindy/Kindy/View Controllers/Home/HomeViewController+CompositionalLayout.swift
  Kindy/Kindy/View Controllers/Home/HomeViewController+DiffableDataSource.swift
  Kindy/Kindy/View Controllers/Home/HomeViewController+Snapshot.swift
  Kindy/Kindy/View Controllers/Home/HomeViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
Labels: refactor

#84 마이페이지에서 내 글, 좋아요 한 글, 댓글 단 글을 볼 수 있는 기능을 추가했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Models/User.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/View Controllers/Login/SignUpViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyActivitiesViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageCurationListViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/Views/MyPage/MyPageTableViewCell.swift
Labels: feature

#85 큐레이션 커뮤니티 탭에 구현되지 않은 기능들을 보완했습니다. + 리팩토링
  Kindy/Kindy/Extensions/UIViewController+.swift
  Kindy/Kindy/Extensions/Utility/Constants.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/View Controllers/FeaturedCurationListViewController.swift
  Kindy/Kindy/Views/CurationList/CurationListCell.swift
Labels: bug, feature, refactor

#86 FirestoreRequest 프로토콜 리팩토링을 통해 반복되는 코드 사용을 줄였습니다.
  Kindy/Kindy/Network Controllers/BookstoreRequest.swift
  Kindy/Kindy/Network Controllers/CommentRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/Protocols/FirestoreRequest.swift
Labels: refactor

#87 큐레이션 작성 페이지 리팩토링
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UIScrollView+.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/View Controllers/Curation/Create/CurationCreateViewController+.swift
  Kindy/Kindy/View Controllers/Curation/Create/CurationCreateViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
Labels: refactor

#88 로그인 뷰의 수정과 마이페이지에서 회원가입 버튼을 삭제하였습니다.
  Kindy/Kindy/Assets.xcassets/KindyIconBorder.imageset/Contents.json
  Kindy/Kindy/Assets.xcassets/KindyIconBorder.imageset/KindyIconBorder.svg
  Kindy/Kindy/View Controllers/Login/SignInViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/Views/Login/SignInView.swift
  Kindy/Kindy/Views/MyPage/TryLoginContainerView.swift
Labels: design
