Repository DeveloperAcademy-POSTECH/MacC-Team-Sandals, pull requests merged in 2022-10, with the labels that each got.

#1 UICollectionViewDiffableDataSource의 ItemIdentifierType인 Item 정의
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Models/BookStore.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/Models/Region.swift
  Kindy/Kindy/Models/TempCuration.swift
  Kindy/Kindy/Protocols/protocol.swift
  Kindy/Kindy/Resources/resource.swift
  Kindy/Kindy/Views/view.swift
Labels: enhancement

#2 큐레이션 상세 페이지의 메인 이미지뷰를 만들었습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Assets.xcassets/testImage.imageset/Contents.json
  Kindy/Kindy/Assets.xcassets/testImage.imageset/Rectangle 9.png
  Kindy/Kindy/Controllers/CurationViewController.swift
  Kindy/Kindy/Extensions/UIViewController+.swift
  Kindy/Kindy/Models/Curation/CurationDetail.swift
  Kindy/Kindy/Models/Curation/CurationMain.swift
  Kindy/Kindy/SceneDelegate.swift
  Kindy/Kindy/Views/Curation/CurationDetailCell.swift
  Kindy/Kindy/Views/Curation/CurationMainView.swift
Labels: feature

#3 홈 화면을 구성할 셀을 정의 후 레이아웃을 구성했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Controllers/HomeViewController.swift
  Kindy/Kindy/Models/Bookstore.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/Models/TempCuration.swift
  Kindy/Kindy/Protocols/protocol.swift
  Kindy/Kindy/Resources/resource.swift
  Kindy/Kindy/Views/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/MainCurationCollectionViewCell.swift
  Kindy/Kindy/Views/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/RegionCollectionViewCell.swift
  Kindy/Kindy/Views/ViewFile.swift
  Kindy/Kindy/Views/view.swift
Labels: feature

#5 홈 화면 섹션 헤더를 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Controllers/HomeViewController.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/Protocols/SectionHeaderDelegate.swift
  Kindy/Kindy/Views/Home/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/Home/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/MainCurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/RegionCollectionViewCell.swift
  Kindy/Kindy/Views/Supplementary/SectionHeaderView.swift
Labels: feature

#4 내 주변 서점 목록 페이지를 생성 및 구현하였습니다. (TableView, Cell, DataSource, Delegate, SearchController 등)
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Controllers/Nearby/NearbyCell.swift
  Kindy/Kindy/Controllers/Nearby/NearbyDummy.swift
  Kindy/Kindy/Controllers/Nearby/NearbyViewController.swift
  Kindy/Kindy/SceneDelegate.swift
Labels: feature

#7 nearby 브랜치를 main 브랜치에 머지하는 과정에서 생긴 충돌 이슈를 해결하였습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Controllers/NearbyViewController.swift
  Kindy/Kindy/Models/Nearby/NearbyDummy.swift
  Kindy/Kindy/Views/Nearby/NearbyCell.swift
Labels: bug

#8 NearbyViewController 에서 쓰인 extension들을 분리하여 Extensions 폴더에 정리하였습니다. ( dismissKeyboard, setEmptyView, setUnderline )
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Controllers/NearbyViewController.swift
  Kindy/Kindy/Extensions/UIButton+.swift
  Kindy/Kindy/Extensions/UITableView+.swift
  Kindy/Kindy/Extensions/UIViewController+.swift
Labels: refactor

#9 🍿 코딩 컨벤션을 적용했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Protocols/ProtocolFile.swift
  Kindy/Kindy/View Controllers/CurationViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/MyPageViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/Views/Home/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/Home/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/MainCurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/RegionCollectionViewCell.swift
  Kindy/Kindy/Views/Supplementary/SectionHeaderView.swift
Labels: refactor

#10 네비게이션 바 버튼 및 델리게이트를 구현했습니다.
  Kindy/Kindy/View Controllers/HomeViewController.swift
Labels: feature

#12 DetailBookstore의 레이아웃을 구성했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Assets.xcassets/instagramIcon.imageset/Contents.json
  Kindy/Kindy/Assets.xcassets/instagramIcon.imageset/InstagramIcon.svg
  Kindy/Kindy/Assets.xcassets/kindyGray.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/kindyGreen.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/kindyLightGray.colorset/Contents.json
  Kindy/Kindy/Extensions/UILabel+.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/Views/DetailBookstoreView.swift
Labels: feature

#14 북마크페이지
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Protocols/BookmarkDelegate.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Bookmark/ImageCarouselCollectionViewCell.swift
Labels: feature

#15 내 주변 서점 섹션과 북마크한 서점 섹션의 예외처리(권한 없거나, 아이템 0개일때)를 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UIButton+.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Home/EmptyBookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Home/EmptyNearbyCollectionViewCell.swift
Labels: feature

#18 DetailBookstore의 네비게이션 바에 적용되는 애니메이션을 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/Views/DetailBookstoreView.swift
Labels: feature

#19 프로젝트에 Firebase를 추가했습니다.
  .gitignore
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kindy/Kindy/AppDelegate.swift
  Kindy/Kindy/GoogleService-Info.plist
Labels: feature

#20 마이페이지 뷰를 구현하였습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Models/Privacy.swift
  Kindy/Kindy/View Controllers/DetailMyPageViewController.swift
  Kindy/Kindy/View Controllers/MyPageViewController.swift
  Kindy/Kindy/Views/MyPage/DetailMyPageView.swift
  Kindy/Kindy/Views/MyPage/MyPageTableViewCell.swift
Labels: feature

#21 큐레이션 페이지를 바텀 시트를 이용해서 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UIViewController+.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Curation/CurationDetail.swift
  Kindy/Kindy/Models/Curation/CurationHeader.swift
  Kindy/Kindy/View Controllers/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/CurationViewController.swift
  Kindy/Kindy/View Controllers/PagingCurationViewController.swift
  Kindy/Kindy/Views/Curation/CurationDetailCell.swift
  Kindy/Kindy/Views/Curation/CurationHeaderView2.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
Labels: feature

#22 북마크 페이지 버그 수정
  Kindy/Kindy/Protocols/BookmarkDelegate.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
Labels: bug

#23 자잘한 디자인 수정과 데이터 모델을 연결했습니다.
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/View Controllers/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/CurationViewController.swift
  Kindy/Kindy/View Controllers/PagingCurationViewController.swift
  Kindy/Kindy/Views/Curation/CurationDetailCell.swift
  Kindy/Kindy/Views/Curation/CurationHeaderView.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
Labels: feature

#24 Bookstore 모델 변경 및 Bookstore 타입을 이용하는 코드를 변경 사항에 맞게 수정했습니다.
  Kindy/Kindy/Models/Bookstore.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/Views/DetailBookstoreView.swift
Labels: feature

#25 세로모드 고정, 다크모드 제한, 최소지원버전 및 디자인 수정을 하였습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/AppDelegate.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/MyPageViewController.swift
  Kindy/Kindy/View Controllers/PagingCurationViewController.swift
Labels: documentation

#26 홈 화면 UI를 보강했습니다. + 간단한 리팩토링을 했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Models/Curation.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Detail/DetailBookstoreView.swift
  Kindy/Kindy/Views/Home/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/Home/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/EmptyBookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Home/EmptyNearbyCollectionViewCell.swift
  Kindy/Kindy/Views/Home/MainCurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NoPermissionCollectionViewCell.swift
  Kindy/Kindy/Views/Home/RegionCollectionViewCell.swift
  Kindy/Kindy/Views/Supplementary/SectionHeaderView.swift
Labels: refactor, design

#28 '독립서점 제보하기' 버튼의 메일 기능을 구현하였습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UITableView+.swift
  Kindy/Kindy/Extensions/UIView+.swift
  Kindy/Kindy/Extensions/UIViewController+.swift
  Kindy/Kindy/Views/EmptyView/EmptyView.swift
Labels: feature

#33 홈 서치, 내 주변 서점, 지역 서점에서 네비게이션 바 투명해지는 이슈를 해결했습니다.
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/114.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/120 1.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/120.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/180.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/40.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/58.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/60.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/80.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/87.png
  Kindy/Kindy/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
Labels: feature, design

#34 enum 초기화 함수를 추가함으로서, HomeView 나올때 데이터 업데이트 적용
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/Models/NewItems.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
Labels: bug

#35 네비게이션 바 UI를 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Extensions/UIImage+.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
Labels: feature, design
