Repository DeveloperAcademy-POSTECH/MacC-Team-Sandals, pull requests merged in 2022-11, with the labels that each got.

#36 UIFont, UIColor extension을 추가했습니다. + 파일, 폴더 구조 수정했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Assets.xcassets/Colors/AccentColor.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/Colors/Contents.json
  Kindy/Kindy/Assets.xcassets/Colors/kindyGray.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/Colors/kindyLightGray.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/Colors/kindyPrimaryGreen.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/Colors/kindySecondaryGreen.colorset/Contents.json
  Kindy/Kindy/Assets.xcassets/Colors/kindySecondaryLightGreen.colorset/Contents.json
  Kindy/Kindy/Extensions/Resources/Privacy.swift
  Kindy/Kindy/Extensions/UIColor+.swift
  Kindy/Kindy/Extensions/UIFont+.swift
  Kindy/Kindy/Extensions/UIImage+.swift
  Kindy/Kindy/Models/Bookstore/Bookstore.swift
  Kindy/Kindy/Models/Bookstore/BusinessHour.swift
  Kindy/Kindy/Models/Bookstore/Location.swift
  Kindy/Kindy/Models/Curation.swift
  Kindy/Kindy/Models/Region.swift
  Kindy/Kindy/Resources/ResourcesFile.swift
  Kindy/Kindy/SceneDelegate.swift
  Kindy/Kindy/View Controllers/Curation/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/My Page/DetailMyPageViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/Views/Home/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/Home/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/EmptyBookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Home/EmptyNearbyCollectionViewCell.swift
  Kindy/Kindy/Views/Home/MainCurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NoPermissionCollectionViewCell.swift
  Kindy/Kindy/Views/Home/RegionCollectionViewCell.swift
  Kindy/Kindy/Views/Supplementary/SectionHeaderView.swift
Labels: refactor

#37 🍿 피드백 내용과 컬러 폰트로 인해 코드를 수정하였습니다.
  Kindy/Kindy/Extensions/UIView+.swift
  Kindy/Kindy/Extensions/UIViewController+.swift
  Kindy/Kindy/View Controllers/Curation/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/Views/Curation/CurationDetailCell.swift
  Kindy/Kindy/Views/Curation/CurationHeaderView.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
Labels: refactor

#38 북마크페이지 첫번째 스프린트 피드백 반영
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Bookmark/BookmarkSectionHeaderView.swift
Labels: refactor

#39 🍿테스트플라이트 피드백을 반영했습니다.
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Home/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/Supplementary/SectionHeaderView.swift
Labels: design

#40 🍿 홈 검색 화면, 내 주변 서점 목록, 지역별 서점 목록에 테스트 플라이트 피드백을 반영했습니다.
  Kindy/Kindy/Extensions/UIViewController+.swift
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
  Kindy/Kindy/Views/EmptyView/EmptyView.swift
  Kindy/Kindy/Views/HomeSearch/HomeSearchCell.swift
  Kindy/Kindy/Views/Nearby/NearbyCell.swift
  Kindy/Kindy/Views/Region/RegionCell.swift
  Kindy/Kindy/Views/Region/RegionHeaderView.swift
Labels: refactor

#41 위치 정보를 받아오는 위치 매니저를 생성하였습니다. 그리고 조금의 마진 수정
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Info.plist
  Kindy/Kindy/Managers/LocationManager.swift
  Kindy/Kindy/Models/Bookstore/Bookstore.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
  개인정보 처리 방침.md
Labels: feature, design

#42 검색 기능을 강화했습니다.
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
Labels: feature

#43 FirebaseManager를 만들고 연동했습니다. (+ 이미지 fetching 추가)
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/AppDelegate.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Managers/LocationManager.swift
  Kindy/Kindy/Models/Bookstore/Bookstore.swift
  Kindy/Kindy/Models/Bookstore/BusinessHour.swift
  Kindy/Kindy/Models/Bookstore/Contact.swift
  Kindy/Kindy/Models/Bookstore/Location.swift
  Kindy/Kindy/Models/Curation.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Curation/Description.swift
  Kindy/Kindy/Models/Home/Model.swift
  Kindy/Kindy/Models/Home/ViewModel.swift
  Kindy/Kindy/Models/Item.swift
  Kindy/Kindy/Models/NewItems.swift
  Kindy/Kindy/Models/Region.swift
  Kindy/Kindy/Models/User.swift
  Kindy/Kindy/Models/test.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Curation/CurationHeaderView.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
  Kindy/Kindy/Views/Detail/DetailBookstoreView.swift
  Kindy/Kindy/Views/Home/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/Home/BookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/CurationCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/RegionCollectionViewCell.swift
  Kindy/Kindy/Views/HomeSearch/HomeSearchCell.swift
  Kindy/Kindy/Views/Nearby/NearbyCell.swift
  Kindy/Kindy/Views/Region/RegionCell.swift
Labels: feature, refactor

#44 내 주변 서점 탐색 기능을 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/CLLocationCoordinate2D+.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Managers/LocationManager.swift
  Kindy/Kindy/Models/Bookstore/Bookstore.swift
  Kindy/Kindy/Models/test.swift 21-58-43-141.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Nearby/NearbyCell.swift
  Kindy/Kindy/Views/Supplementary/SectionHeaderView.swift
Labels: feature

#46 위치 권한 없을 때의 셀을 추가 + 리프레쉬 컨트롤 추가 + 유저를 이메일로 fetch 해오는 함수 구현했습니다.
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Models/Home/ViewModel.swift
  Kindy/Kindy/Models/User.swift
  Kindy/Kindy/Models/test.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Detail/DetailBookstoreView.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCollectionViewCell.swift
  Kindy/Kindy/Views/Home/NoPermissionCollectionViewCell.swift
Labels: feature

#47 홈 검색 페이지, 내 주변 서점 목록 페이지, 지역별 서점 목록 페이지에 홈에서 넘겨주는 데이터를 받는 메소드를 구현했습니다.
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
Labels: refactor

#51 북마크 섹션을 다시 추가했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Models/Home/Model.swift
  Kindy/Kindy/Models/Home/ViewModel.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/Views/Home/BookmarkedCollectionViewCell.swift
  Kindy/Kindy/Views/Home/ExceptionBookmarkCollectionViewCell.swift
Labels: feature

#52 유저 삭제 기능 추가 및 기타 버그 픽스
  Kindy/Kindy/Extensions/Resources/Privacy.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/Login/PolicySheetViewController.swift
  Kindy/Kindy/View Controllers/Login/SignInViewController.swift
  Kindy/Kindy/View Controllers/Login/SignUpViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
Labels: feature

#55 서점 상세 정보 수정 및 이미지 불러오기 기능 추가
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Assets.xcassets/backButton.imageset/Contents.json
  Kindy/Kindy/Assets.xcassets/backButton.imageset/back.svg
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Managers/ImageCacheManager.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/Views/Detail/DetailBookstoreView.swift
Labels: feature

#57 SignInViewController에서 유저 정보 확인 로직 분리
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Protocols/SignInDelegate.swift
  Kindy/Kindy/View Controllers/Login/PolicySheetViewController.swift
  Kindy/Kindy/View Controllers/Login/SignInViewController.swift
  Kindy/Kindy/View Controllers/Login/SignUpViewController.swift
  Kindy/Kindy/Views/Login/CheckPolicyUIView.swift
  Kindy/Kindy/Views/Login/CheckboxUIView.swift
  Kindy/Kindy/Views/SignIn/SignInView.swift
Labels: refactor

#59 리팩토링 SignUp 및 자잘한 성능 개선 및 네이밍 수정
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UIButton+.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Protocols/SignUpDelegate.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/View Controllers/Login/SignUpViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Login/SignInView.swift
  Kindy/Kindy/Views/Login/SignUpComponent/CheckPolicyUIView.swift
  Kindy/Kindy/Views/Login/SignUpComponent/CheckboxUIView.swift
  Kindy/Kindy/Views/Login/SignUpView.swift
Labels: refactor

#60 🍿 홈 뷰컨트롤러의 네트워킹 코드 및 디테일들을 수정했습니다.
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Models/Home/Model.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
Labels: refactor, design

#62 북마크리스트페이지에서 상세페이지 이동후 북마크 해제한 후 북마크 리스트에서 적용안되는 버그 수정
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
Labels: bug

#64 Curation 좋아요 기능 구현, 버그수정 및 내부 레이아웃 리팩토링
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/LoginCheckable+.swift
  Kindy/Kindy/Extensions/Notification+.swift
  Kindy/Kindy/Extensions/Reportable+.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Protocols/LoginCheckable.swift
  Kindy/Kindy/Protocols/Reportable.swift
  Kindy/Kindy/View Controllers/Curation/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/View Controllers/Login/SignInViewController.swift
  Kindy/Kindy/View Controllers/Login/SignUpViewController.swift
  Kindy/Kindy/Views/Curation/CurationButtonItem.swift
  Kindy/Kindy/Views/Curation/CurationButtonStackView.swift
  Kindy/Kindy/Views/Curation/CurationDetailCell.swift
  Kindy/Kindy/Views/Curation/CurationHeaderView.swift
  Kindy/Kindy/Views/Curation/CurationLayout.swift
  Kindy/Kindy/Views/Curation/CurationReplyCell.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
Labels: bug, feature, refactor

#66 이미지 캐싱(메모리, 디스크-임시)을 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/AppDelegate.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Managers/ImageCacheManager.swift
  Kindy/Kindy/Models/Home/ViewModel.swift
  Kindy/Kindy/Models/ImageCache.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
  Kindy/Kindy/Views/Home/BookmarkedBookstoreCell.swift
  Kindy/Kindy/Views/Home/CurationCell.swift
  Kindy/Kindy/Views/Home/EmptyNearbyCell.swift
  Kindy/Kindy/Views/Home/ExceptionBookmarkCell.swift
  Kindy/Kindy/Views/Home/FeaturedBookstoreCell.swift
  Kindy/Kindy/Views/Home/NearByBookstoreCell.swift
  Kindy/Kindy/Views/Home/NoPermissionCell.swift
  Kindy/Kindy/Views/Home/RegionNameCell.swift
Labels: documentation, feature

#68 큐레이션 커뮤니티 기능 (큐레이션 목록 페이지) 를 구현했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kindy/Kindy/Assets.xcassets/bookstoreCategory.imageset/Contents.json
  Kindy/Kindy/Assets.xcassets/bookstoreCategory.imageset/category:bookstore 1.svg
  Kindy/Kindy/Assets.xcassets/bookstoreCategory.imageset/category:bookstore 2.svg
  Kindy/Kindy/Assets.xcassets/bookstoreCategory.imageset/category:bookstore.svg
  Kindy/Kindy/Base.lproj/Main.storyboard
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/View Controllers/FeaturedCurationListViewController.swift
  Kindy/Kindy/Views/CurationList/CurationCategoryButton.swift
  Kindy/Kindy/Views/CurationList/CurationListCell.swift
  Kindy/Kindy/Views/CurationList/CurationListHeaderView.swift
Labels: feature

#69 FirestoreManager를 3개의 구조체로 분리했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kindy/Kindy/Extensions/Resources/Constants.swift
  Kindy/Kindy/Extensions/Utility/Constants.swift
  Kindy/Kindy/Extensions/Utility/Privacy.swift
  Kindy/Kindy/Managers/FirestoreManager.swift
  Kindy/Kindy/Models/Curation/Comment.swift
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Home/Model.swift
  Kindy/Kindy/Models/ImageCache.swift
  Kindy/Kindy/Network Controllers/BookstoreRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/Protocols/Delegates/BookmarkDelegate.swift
  Kindy/Kindy/Protocols/Delegates/CheckPolicyDelegate.swift
  Kindy/Kindy/Protocols/Delegates/SectionHeaderDelegate.swift
  Kindy/Kindy/Protocols/Delegates/SignInDelegate.swift
  Kindy/Kindy/Protocols/Delegates/SignUpDelegate.swift
  Kindy/Kindy/Protocols/FirestoreRequest.swift
  Kindy/Kindy/View Controllers/BookmarkViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/View Controllers/DetailBookstoreViewController.swift
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/Login/SignInViewController.swift
  Kindy/Kindy/View Controllers/Login/SignUpViewController.swift
  Kindy/Kindy/View Controllers/My Page/EditNicknameViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/View Controllers/NearbyViewController.swift
  Kindy/Kindy/View Controllers/RegionViewController.swift
  Kindy/Kindy/Views/Bookmark/BookmarkCollectionViewCell.swift
  Kindy/Kindy/Views/Curation/CurationButtonItem.swift
  Kindy/Kindy/Views/Curation/CurationStoreCell.swift
Labels: refactor

#70 Curation 추가 페이지 작성
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Models/Curation/Curation.swift
  Kindy/Kindy/Models/Curation/Description.swift
  Kindy/Kindy/Protocols/CurationCraeteDelegate.swift
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateAddDescriptionButton.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateDescriptionTableViewCell.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateHeadTextView.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateTitleView.swift
Labels: feature

#71 큐레이션 상세 페이지에 댓글 기능을 구현했습니다
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/Reportable+.swift
  Kindy/Kindy/Extensions/UIColor+.swift
  Kindy/Kindy/Extensions/Utility/Constants.swift
  Kindy/Kindy/Models/Curation/Comment.swift
  Kindy/Kindy/Models/Curation/Curation.swift~HEAD
  Kindy/Kindy/Models/Curation/Curation.swift~develop
  Kindy/Kindy/Network Controllers/CommentRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/Protocols/SignInDelegate.swift~develop
  Kindy/Kindy/Protocols/SignUpDelegate.swift~HEAD
  Kindy/Kindy/Protocols/SignUpDelegate.swift~develop
  Kindy/Kindy/View Controllers/Curation/BottomSheetViewController.swift
  Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
  Kindy/Kindy/View Controllers/Curation/PagingCurationViewController.swift
  Kindy/Kindy/Views/Curation/CurationButtonItem.swift
  Kindy/Kindy/Views/Curation/CurationButtonStackView.swift
  Kindy/Kindy/Views/Curation/CurationCommentCell.swift
  Kindy/Kindy/Views/Curation/CurationCommentTextFieldCell.swift
  Kindy/Kindy/Views/Curation/CurationDetailCell.swift
  Kindy/Kindy/Views/Curation/CurationTextCell.swift
Labels: feature

#72 큐레이션 커뮤니티 탭의 검색 기능을 구현하고, 큐레이션 목록 페이지 코드를 수정하였습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/UITableView+.swift
  Kindy/Kindy/View Controllers/CurationListViewController.swift
  Kindy/Kindy/View Controllers/FeaturedCurationListViewController.swift
  Kindy/Kindy/View Controllers/HomeSearchViewController.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
  Kindy/Kindy/View Controllers/SearchViewController.swift
  Kindy/Kindy/Views/CurationList/CurationCategoryButton.swift
  Kindy/Kindy/Views/CurationList/CurationListCell.swift
  Kindy/Kindy/Views/CurationList/CurationListHeaderView.swift
Labels: feature

#73 마이페이지의 버그 수정 및 내부 리팩토링
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/View Controllers/My Page/EditNicknameViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyActivitiesViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyWritingViewController.swift
  Kindy/Kindy/Views/MyPage/DetailMyPageView.swift
  Kindy/Kindy/Views/MyPage/EditNicknameView.swift
  Kindy/Kindy/Views/MyPage/MyPageTableViewCell.swift
  Kindy/Kindy/Views/MyPage/TryLoginContainerView.swift
  Kindy/Kindy/Views/MyPage/UserInfoContainerView.swift
Labels: refactor

#75 🍿 (업데이트를 위한) 홈 디테일 수정
  Kindy/Kindy/Extensions/Utility/Constants.swift
  Kindy/Kindy/Network Controllers/BookstoreRequest.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/Network Controllers/UserManager.swift
  Kindy/Kindy/View Controllers/HomeViewController.swift
Labels: refactor, design

#74 큐레이션 추가/ 삭제 로직 추가
  Kindy/Kindy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/View Controllers/Curation/CurationCreateViewController.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateAddDescriptionButton.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateDescriptionTableViewCell.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateHeadTextView.swift
  Kindy/Kindy/Views/Curation/Create/CurationCreateTitleView.swift
Labels: feature

#76 동시에 image를 fetch 하는 로직을 추가 하였습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Extensions/Sequence+.swift
  Kindy/Kindy/Models/ImageCache.swift
Labels: feature

#78 마이페이지에 내 글과 활동내역 기능을 추가했습니다.
  Kindy/Kindy.xcodeproj/project.pbxproj
  Kindy/Kindy/Models/ImageCache.swift
  Kindy/Kindy/Network Controllers/CurationRequest.swift
  Kindy/Kindy/View Controllers/My Page/MyActivitiesViewController.swift
  Kindy/Kindy/View Controllers/My Page/MyPageViewController.swift
  Kindy/Kindy/View Controllers/My Page/WritingListViewController.swift
  Kindy/Kindy/Views/MyPage/MyPageTableViewCell.swift
  Kindy/Kindy/Views/MyPage/NoWritingView.swift
  Kindy/Kindy/Views/MyPage/UserInfoContainerView.swift
Labels: feature
